name: Deploy PROD

on:
  workflow_dispatch:


env:
  NODE_ENV: production
  STAGE: prod
  AWS_REGION: ap-northeast-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
  deploy-start:
    name: Deploy Start
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

  build-push:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: [ deploy-start ]
    steps:
      - uses: actions/checkout@v3
        with:
            ref: ${{ github.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Set up NPM authentication
        run: npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node Modules
        run: yarn install --production=false
      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn build
      - name: Deploy Serverless
        run: npx sls deploy --stage prod